id: circular-config-detection
title: Circular Config Detection
test:
  - name: "Circular config detection error"
    options:
      command: 'npx tsx --no-cache --tsconfig ../tsconfig.json cli.ts'
    assertions:
      exitCode: 1
      stderr:
        contains: 'Circular reference detected'
