id: circular-config-detection
title: Circular Config Detection
hidden: true
entryPoint: cli.ts
fileMap:
  './cli.ts': 'cli.ts'
  './a.config.json': 'a.config.json'
  './b.config.json': 'b.config.json'
test:
  - name: "Circular config detection error"
    options:
      command: 'tsx --no-cache --tsconfig ./examples/tsconfig.json {entryPoint}'
    assertions:
      exitCode: 1
      stderr:
        contains: 'Circular reference detected'
