name: PR Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    name: Build and Test (${{ matrix.os }})

    env:
      NX_CI_EXECUTION_ENV: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Print Task Graph
        run: npx nx run-many -t build test e2e --graph stdout

      - name: Run tests
        run: npx nx run-many -t build test e2e
